// Generated by CoffeeScript 1.7.1
(function() {
  define((function() {
    var makeWireframe;
    makeWireframe = function(settings, radius, height, segments) {
      var geometry, material;
      geometry = new THREE.CylinderGeometry(radius, radius, height, segments, 1, true);
      material = new THREE.MeshBasicMaterial({
        color: settings.color3(),
        wireframe: true,
        transparent: true,
        opacity: settings.opacity
      });
      return new THREE.Mesh(geometry, material);
    };
    return function(settings) {
      var wireframes;
      wireframes = new THREE.Object3D();
      wireframes.add(makeWireframe(settings.wireframes, 1, 25, 3));
      wireframes.add(makeWireframe(settings.wireframes, 0.5, 50, 6));
      wireframes.add(makeWireframe(settings.wireframes, 20, 2, 32));
      return wireframes;
    };
  }));

}).call(this);

//# sourceMappingURL=debugWireframes.map
