// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var makeBeam, makeBeams, makeCylinder;
    makeCylinder = function(radius, height, color, opacity) {
      var geometry, material;
      geometry = new THREE.CylinderGeometry(radius, radius, height, 32);
      material = new THREE.MeshBasicMaterial({
        color: color,
        transparent: true,
        opacity: opacity
      });
      return new THREE.Mesh(geometry, material);
    };
    makeBeam = function(radius, height, steps, stepSize, color, opacity) {
      var beam, x;
      opacity = opacity / steps;
      beam = new THREE.Object3D();
      while (steps -= 1) {
        x = makeCylinder(radius, height, color, opacity);
        beam.add(x);
        radius -= stepSize;
      }
      return beam;
    };
    makeBeams = function(settings) {
      var beam, heightFactor, n, pillar, translateSpread;
      pillar = new THREE.Object3D();
      n = settings.quantity;
      while (n -= 1) {
        heightFactor = THREE.Math.randFloat(1, 4);
        translateSpread = (4 - heightFactor) * settings.scale;
        beam = makeBeam(0.1 * settings.scale, Math.pow(heightFactor, 3) * settings.scale, 2, 0.05 * settings.scale, settings.color3(), settings.opacity);
        beam.translateX(THREE.Math.randFloatSpread(translateSpread));
        beam.translateZ(THREE.Math.randFloatSpread(translateSpread));
        pillar.add(beam);
      }
      return pillar;
    };
    return function(settings) {
      var lightPillar;
      lightPillar = new THREE.Object3D();
      lightPillar.add(makeBeams(settings.beamClouds));
      return lightPillar;
    };
  });

}).call(this);

//# sourceMappingURL=lightPillar.map
