// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var build, makeStar, makeStarField;
    makeStar = function(minDist, maxDist) {
      var phi, r, theta;
      r = THREE.Math.randFloat(minDist, maxDist);
      theta = THREE.Math.randFloat(0, 2 * Math.PI);
      phi = THREE.Math.randFloat(0, 2 * Math.PI);
      return new THREE.Vector3(r * Math.sin(theta) * Math.cos(phi), r * Math.sin(theta) * Math.sin(phi), r * Math.cos(theta));
    };
    makeStarField = function(min, max, n) {
      var geometry, material;
      geometry = new THREE.Geometry();
      while (n -= 1) {
        geometry.vertices.push(makeStar(min, max));
      }
      material = new THREE.PointCloudMaterial({
        color: 0xffffff,
        size: 0.1
      });
      return new THREE.PointCloud(geometry, material);
    };
    build = function(settings) {
      var starField;
      starField = new THREE.Object3D();
      starField.add(makeStarField(750, 1000, settings.num_stars));
      return starField;
    };
    return build;
  });

}).call(this);

//# sourceMappingURL=starField.map
