// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var Settings, disk, gui, misc, onFinishChange, pillar, settings;
    Settings = function() {
      this.pillar_particles = 1000;
      this.pillar_beams = 1000;
      this.pillar_scale = 1;
      this.pillar_color = "#FFDD99";
      this.num_stars = 1000;
      this.disk_particles = 15000;
      this.disk_clouds = 1000;
      this.disk_scale = 1;
      this.disk_color = "#FFBBAA";
      return this.wireframes = false;
    };
    settings = new Settings;
    gui = new dat.GUI;
    pillar = gui.addFolder("Light Pillar");
    disk = gui.addFolder("Accretion Disk");
    misc = gui.addFolder("Miscellaneous");
    pillar.add(settings, 'pillar_particles', 0, 5000);
    pillar.add(settings, 'pillar_beams', 0, 5000);
    pillar.add(settings, 'pillar_scale', 0, 5);
    pillar.add(settings, 'pillar_color', 'color0');
    disk.add(settings, 'disk_particles', 0, 50000);
    disk.add(settings, 'disk_clouds', 0, 5000);
    disk.add(settings, 'disk_scale', 0, 5);
    disk.add(settings, 'disk_color', 'color0');
    misc.add(settings, 'num_stars', 0, 5000);
    misc.add(settings, 'wireframes');
    pillar.open();
    disk.open();
    misc.open();
    onFinishChange = function(f) {
      var ctrl, folder, _i, _len, _ref, _results;
      _ref = [pillar, disk, misc];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        folder = _ref[_i];
        _results.push((function() {
          var _j, _len1, _ref1, _results1;
          _ref1 = folder.__controllers;
          _results1 = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            ctrl = _ref1[_j];
            _results1.push(ctrl.onFinishChange(f));
          }
          return _results1;
        })());
      }
      return _results;
    };
    return {
      settings: settings,
      gui: gui,
      onFinishChange: onFinishChange
    };
  });

}).call(this);

//# sourceMappingURL=config.map
