// Generated by CoffeeScript 1.7.1
(function() {
  require(["builders/debugWireframes", "builders/accretionDisk", "builders/lightPillar", "builders/starField", "config"], function(debugWireframes, accretionDisk, lightPillar, starField, settings) {
    var init, initCamera, initControls, initRenderer, initStats, rebuild;
    initCamera = function() {
      var camera;
      camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 4000);
      camera.position.z = 50;
      return camera;
    };
    initRenderer = function() {
      var renderer;
      renderer = new THREE.WebGLRenderer();
      renderer.setSize(window.innerWidth, window.innerHeight);
      document.body.appendChild(renderer.domElement);
      return renderer;
    };
    initControls = function(camera, element, onChange) {
      var controls;
      controls = new THREE.TrackballControls(camera, element);
      controls.rotateSpeed = 1.0;
      controls.zoomSpeed = 1.2;
      controls.panSpeed = 0.8;
      controls.noZoom = false;
      controls.noPan = false;
      controls.staticMoving = true;
      controls.dynamicDampingFactor = 0.3;
      controls.keys = [65, 83, 68];
      controls.addEventListener('change', onChange);
      return controls;
    };
    initStats = function() {
      var stats;
      stats = new Stats;
      stats.setMode(1);
      stats.domElement.style.position = 'absolute';
      stats.domElement.style.left = '0px';
      stats.domElement.style.top = '0px';
      document.body.appendChild(stats.domElement);
      return stats;
    };
    rebuild = function(config) {
      var scene;
      scene = new THREE.Scene();
      scene.add(debugWireframes(config));
      scene.add(accretionDisk(config));
      scene.add(lightPillar(config));
      scene.add(starField(config));
      return scene;
    };
    init = function() {
      var animate, camera, controls, render, renderer, scene, stats;
      stats = initStats();
      scene = new THREE.Scene;
      camera = initCamera();
      renderer = initRenderer();
      render = function() {
        return renderer.render(scene, camera);
      };
      controls = initControls(camera, renderer.domElement, render);
      animate = function() {
        stats.begin();
        requestAnimationFrame(animate);
        controls.update();
        return stats.end();
      };
      return animate();
    };
    return init();
  });

}).call(this);

//# sourceMappingURL=init.map
