// Generated by CoffeeScript 1.7.1
(function() {
  require(["builders/accretionDisk", "builders/lightPillar", "builders/starField"], function(accretionDisk, lightPillar, starField) {
    var init, initCamera, initControls, initRenderer, initViewModel, rebuild;
    initCamera = function() {
      var camera;
      camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
      camera.position.z = 50;
      return camera;
    };
    initRenderer = function() {
      var renderer;
      renderer = new THREE.WebGLRenderer();
      renderer.setSize(window.innerWidth, window.innerHeight);
      document.body.appendChild(renderer.domElement);
      return renderer;
    };
    initControls = function(camera, element, onChange) {
      var controls;
      controls = new THREE.TrackballControls(camera, element);
      controls.rotateSpeed = 1.0;
      controls.zoomSpeed = 1.2;
      controls.panSpeed = 0.8;
      controls.noZoom = false;
      controls.noPan = false;
      controls.staticMoving = true;
      controls.dynamicDampingFactor = 0.3;
      controls.keys = [65, 83, 68];
      controls.addEventListener('change', onChange);
      return controls;
    };
    rebuild = function(settings) {
      var scene;
      scene = new THREE.Scene();
      accretionDisk(scene, settings);
      lightPillar(scene, settings);
      starField(scene, settings);
      return scene;
    };
    initViewModel = function() {
      return {
        settings: ko.observable({
          num_particles: 5000,
          num_beams: 1000,
          num_stars: 1000,
          show_wireframe: false
        })
      };
    };
    init = function() {
      var animate, camera, controls, render, renderer, scene, viewModel;
      scene = new THREE.Scene();
      camera = initCamera();
      renderer = initRenderer();
      render = function() {
        return renderer.render(scene, camera);
      };
      controls = initControls(camera, renderer.domElement, render);
      animate = function() {
        requestAnimationFrame(animate);
        return controls.update();
      };
      viewModel = initViewModel();
      ko.applyBindings(viewModel);
      viewModel.settings.subscribe(function(s) {
        scene = rebuild(s);
        return render();
      });
      viewModel.settings.valueHasMutated();
      render();
      return animate();
    };
    return init();
  });

}).call(this);

//# sourceMappingURL=init.map
