// Generated by CoffeeScript 1.7.1
(function() {
  require(["builders/debugWireframes", "builders/accretionDisk", "builders/lightPillar", "builders/starField", "settings"], function(debugWireframes, accretionDisk, lightPillar, starField, settings) {
    var init, initCamera, initControls, initRenderer, rebuild;
    initCamera = function() {
      var camera;
      camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
      camera.position.z = 50;
      return camera;
    };
    initRenderer = function() {
      var renderer;
      renderer = new THREE.WebGLRenderer();
      renderer.setSize(window.innerWidth, window.innerHeight);
      document.body.appendChild(renderer.domElement);
      return renderer;
    };
    initControls = function(camera, element, onChange) {
      var controls;
      controls = new THREE.TrackballControls(camera, element);
      controls.rotateSpeed = 1.0;
      controls.zoomSpeed = 1.2;
      controls.panSpeed = 0.8;
      controls.noZoom = false;
      controls.noPan = false;
      controls.staticMoving = true;
      controls.dynamicDampingFactor = 0.3;
      controls.keys = [65, 83, 68];
      controls.addEventListener('change', onChange);
      return controls;
    };
    rebuild = function(settings) {
      var scene;
      scene = new THREE.Scene();
      scene.add(debugWireframes(settings));
      scene.add(accretionDisk(settings));
      scene.add(lightPillar(settings));
      scene.add(starField(settings));
      return scene;
    };
    init = function() {
      var animate, camera, controls, render, renderer, scene, viewModel;
      scene = new THREE.Scene();
      camera = initCamera();
      renderer = initRenderer();
      render = function() {
        return renderer.render(scene, camera);
      };
      controls = initControls(camera, renderer.domElement, render);
      animate = function() {
        requestAnimationFrame(animate);
        return controls.update();
      };
      viewModel = {
        settings: ko.observable(settings)
      };
      viewModel.updateQuasar = function() {
        scene = rebuild(viewModel.settings());
        return render();
      };
      viewModel.colorPicker = function(data, event) {
        colorPicker.exportColor = function() {
          return data.color = "#" + colorPicker.CP.hex;
        };
        return colorPicker(event);
      };
      viewModel.showSettings = ko.observable(true);
      viewModel.toggleSettings = function() {
        return viewModel.showSettings(!viewModel.showSettings());
      };
      ko.applyBindings(viewModel);
      viewModel.updateQuasar();
      return animate();
    };
    return init();
  });

}).call(this);

//# sourceMappingURL=init.map
