// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var makeSetting;
    makeSetting = function(displayName, defaults) {
      var setting, _ref, _ref1, _ref2, _ref3;
      if (defaults == null) {
        defaults = {};
      }
      setting = {
        _displayName: displayName,
        quantity: (_ref = defaults.quantity) != null ? _ref : 1,
        color: (_ref1 = defaults.color) != null ? _ref1 : "#FFFFFF",
        opacity: (_ref2 = defaults.opacity) != null ? _ref2 : 1,
        scale: (_ref3 = defaults.scale) != null ? _ref3 : 1
      };
      setting.color3 = (function(_this) {
        return function() {
          return new THREE.Color(setting.color);
        };
      })(this);
      return setting;
    };
    return {
      beamParticles: makeSetting("Beam particles", {
        quantity: 1000
      }),
      beamClouds: makeSetting("Beam clouds", {
        quantity: 1000,
        color: "#FFDD99",
        opacity: 0.05
      }),
      diskClouds: makeSetting("Disk clouds", {
        quantity: 1000
      }),
      diskParticles: makeSetting("Disk particles", {
        quantity: 15000,
        color: "#FFBBAA"
      }),
      wireframes: makeSetting("Debug Wireframes", {
        color: "#FF0000",
        opacity: 0
      }),
      starfield: makeSetting("Starfield", {
        quantity: 1000
      })
    };
  });

}).call(this);

//# sourceMappingURL=settings.map
